services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drf_backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && 
             daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DEBUG=True
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev: