# Generated by Django 5.2.8 on 2025-11-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tableId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
