# Generated by Django 5.2.8 on 2025-11-23 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventoryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='inventoryItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='inventoryMovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='inventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='inventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitemtype')),
                ('movementType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymovementtype')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct')),
            ],
        ),
    ]
