# Generated by Django 5.2.8 on 2025-11-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bill'),
        ),
    ]
