# Generated by Django 5.2.8 on 2025-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_order_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
