# Generated by Django 5.2.8 on 2025-11-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_orderitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tableId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
