# Generated by Django 5.2.8 on 2025-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_order_tableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waiterId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
