# Generated by Django 5.2.8 on 2025-11-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('cashierId', models.CharField(max_length=200)),
            ],
        ),
    ]
