# Generated by Django 5.2.8 on 2025-11-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('preparation_time', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Pasos detallados de la receta')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cookbook_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cookbookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cookbook')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
            ],
        ),
    ]
