# Generated by Django 5.2.8 on 2025-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('mesero_access', 'Acceso Mesero'), ('cocina_access', 'Acceso Cocina'), ('caja_access', 'Acceso Caja'), ('admin_access', 'Acceso Administrador')],
            },
        ),
    ]
